# Generated by Django 4.2 on 2023-04-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instaFollower", "0002_account_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="login",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
